[agent]
  interval = "5m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1m"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
  ## Log at debug level.
  #debug = true
  logtarget = "file"
  logfile = "/var/log/telegraf/telegraf.log"

[[inputs.net]]
  interfaces = ["en*", "wl*"]

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
  mount_points = ["/"]

# Read metrics about disk IO by device
[[inputs.diskio]]

[[inputs.smartctl]]
  interval = "1h"
  path = "/usr/sbin/smartctl"
  use_sudo = true
  # attributes = true
  # devices_include = []
  # devices_exclude = []
  # timeout = "30s"

# Get kernel statistics from /proc/stat
[[inputs.kernel]]

# Read metrics about memory usage
[[inputs.mem]]

# Get the number of processes and group them by status
#[[inputs.processes]]

# Read metrics about swap memory usage
[[inputs.swap]]

# Read metrics about system load & uptime
[[inputs.system]]

# Get kernel statistics from /proc/vmstat
[[inputs.kernel_vmstat]]

[[inputs.temp]]

[[inputs.nvidia_smi]]

[[inputs.infiniband]]

[[inputs.prometheus]]
  ## The array of endpoints to scrape. 
  ## Point this to your vLLM engine instance(s).
  urls = ["http://localhost:8090/metrics"]

  ## Metric version 2 changes the mapping structure to keep it cleaner:
  ## Prometheus metric names become Telegraf field keys.
  metric_version = 2

  ## Tag the data so you can easily separate host metrics from LLM engine metrics
  tags = { app = "vllm", cluster = "gb10" }

  #fieldinclude = [
  #  "vllm:num_requests_running", "vllm:num_requests_waiting", 
  #  "vllm:kv_cache_usage_perc", "vllm:prompt_tokens", 
  #  "vllm:generation_tokens", "vllm:num_preemptions",
  #  "vllm:time_to_first_token_seconds_bucket", "vllm:inter_token_latency_seconds_bucket"
  #]

[[outputs.influxdb]]
  urls = ["http://192.168.0.137:8086"]
  username = "trevor"
  password = "P@ssw0rd!"
  database = "gb10"
  skip_database_creation = false

# Debugging only
#[[outputs.file]]
#  files = ["stdout"]
#  namepass = ["jellyfin-stats"]