model:
  provider: custom
  model: bg-digitalservices/Gemma-4-26B-A4B-it-NVFP4
  base_url: http://192.168.0.30:8090/v1 # vLLM instance or any OpenAI-compatible API endpoint
  api_key: "none" # vLLM doesn't enforce API keys internally

providers:
  custom:
    request_timeout_seconds: 3600
    stale_timeout_seconds: 900

custom_providers: # Use this to be able to switch between multiple LLM backends if you have multiple running. 
  - name: vllm # This feeds the /model command in hermes. It will auto-populate with the current model running in the vLLM instance
    base_url: http://192.168.0.30:8090/v1 # vLLM instance or any OpenAI-compatible API endpoint

auxiliary:
  vision:
    provider: custom
    model: bg-digitalservices/Gemma-4-26B-A4B-it-NVFP4 
    timeout: 9000          # LLM API call timeout (seconds)
    download_timeout: 60   # Image HTTP download timeout (seconds)
                           # Increase for slow connections or self-hosted image servers

agent: 
  default_model: bg-digitalservices/Gemma-4-26B-A4B-it-NVFP4 
  system_prompt: "You are a professional operations assistant capable of precise tool execution, autonomous web scraping, and Python development."

approvals:
  destructive_slash_confirm: false # Disable confirmation. We're running in a docker container so it's less of a risk here.

curator:
  enabled: false # Disable automatic skill updating

sessions:
  auto_prune: true # Automatically prune old sessions to manage storage
  retention_days: 180

display: # These can be adjusted if the terminal is too noisy
  show_reasoning: true 
  tool_progress: "verbose"
  tool_progress_command: true
  tool_preview_length: 200

delegation:
  max_concurrent_children: 4 # Number of concurrent subagents from delegate_task
  max_spawn_depth: 2 # Number of nested subagents from initial delegate_task

timezone: "America/Denver" 

# Uncomment if you wish to use a memory provider
# memory:
#   provider: hindsight

browser:
  auto_local_for_private_urls: true
  allow_private_urls: true 

bundles: # Default tools to enable
  - search_tools
  - coding_assistant
  - system_management

web:
  backend: tavily # firecrawl | parallel | tavily 

logging:
  level: "INFO"

skills:
  external_dirs:
    - /skills # This cooresponds to the docker volume in compose.yaml

mcp_servers: []
