package_list:     
  - unzip
  - lm-sensors
  - wget
  - nvme-cli
  - fio
  - tmux
  - dstat
  - nmap
  - htop
  - btop
  - nvtop
telegraf_conf: telegraf-gb10.conf
sysctl_conf: sysctl-gb10.conf
ssh_keys:
  - pc001_id_ed25519.pub
nfs_mounts:
  - path: "/mnt/gb10"
    src: "192.168.0.100:/srv/nfs/gb10"
    opts: "_netdev,x-systemd.mount-timeout=10,nofail,timeo=14,retrans=2"